Repository Lembas-Modding-Team/pvp-mode, pull requests merged in 2018-07, with the labels that each got.

#169 Changed the PvP timer's default and maximum value
  CHANGELOG.md
  src/main/java/pvpmode/PvPMode.java
Labels: improvement

#172 Added a second warmup timer for disabeling PvP
  CHANGELOG.md
  src/main/java/pvpmode/PvPMode.java
  src/main/java/pvpmode/command/PvPCommand.java
  src/main/java/pvpmode/command/PvPCommandConfig.java
Labels: improvement, new feature

#168 Added optional proximity directions to pvplist
  CHANGELOG.md
  src/main/java/pvpmode/PvPMode.java
  src/main/java/pvpmode/PvPUtils.java
  src/main/java/pvpmode/command/PvPCommandConfig.java
  src/main/java/pvpmode/command/PvPCommandList.java
Labels: improvement

#167 Made long pvplists more manageable
  CHANGELOG.md
  src/main/java/pvpmode/command/PvPCommandHelp.java
  src/main/java/pvpmode/command/PvPCommandList.java
Labels: improvement

#174 Added PvE support to the partial inventory loss
  CHANGELOG.md
  src/main/java/pvpmode/PvPEventHandler.java
  src/main/java/pvpmode/PvPMode.java
  src/main/java/pvpmode/command/PvPCommandConfig.java
Labels: improvement, new feature

#182 Fixed that /pvplist showed the wrong hostile player count
  src/main/java/pvpmode/command/PvPCommandList.java
Labels: bug

#179 Set the PvP Timer to 0 on a player death
  CHANGELOG.md
  src/main/java/pvpmode/PvPEventHandler.java
Labels: bug

#178 Change the help message of /pvplist
  src/main/java/pvpmode/command/PvPCommandHelp.java
Labels: bug

#187 Ingame chat messages are now gender neutral
  CHANGELOG.md
  src/main/java/pvpmode/compatibility/modules/lotr/MiddleEarthBiomeOverrideCondition.java
Labels: improvement

#188 Improved the comments regarding the partial inventory loss config entries
  src/main/java/pvpmode/PvPMode.java
Labels: improvement

#189 Unified the chat messages
  CHANGELOG.md
  src/main/java/pvpmode/PvPEventHandler.java
  src/main/java/pvpmode/command/AbstractPvPCommand.java
  src/main/java/pvpmode/command/PvPCommand.java
  src/main/java/pvpmode/command/PvPCommandAdmin.java
  src/main/java/pvpmode/compatibility/modules/lotr/MiddleEarthBiomeOverrideCondition.java
  src/main/java/pvpmode/overrides/PvPOverrideManager.java
Labels: improvement

#194 Changed "resetted" to "canceled" for warmup timer related messages
  src/main/java/pvpmode/PvPEventHandler.java
Labels: improvement

#192 Improved /pvpadmin
  CHANGELOG.md
  src/main/java/pvpmode/command/PvPCommandAdmin.java
  src/main/java/pvpmode/command/PvPCommandHelp.java
Labels: improvement

#193 Added a message displayed upon cancelation of the warmup timer because of PvP
  CHANGELOG.md
  src/main/java/pvpmode/PvPEventHandler.java
Labels: improvement

#196 Siege Mode Mod Compatibility
  CHANGELOG.md
  src/main/java/pvpmode/PvPEventHandler.java
  src/main/java/pvpmode/PvPMode.java
  src/main/java/pvpmode/command/PvPCommandList.java
  src/main/java/pvpmode/compatibility/ModCompatibilityModuleLoader.java
  src/main/java/pvpmode/compatibility/events/OnPartialInventoryLossEvent.java
  src/main/java/pvpmode/compatibility/events/OnPvPLogEvent.java
  src/main/java/pvpmode/compatibility/events/PvPListEvent.java
  src/main/java/pvpmode/compatibility/modules/lotr/LOTRModCompatibilityModuleLoader.java
  src/main/java/pvpmode/compatibility/modules/siegeMode/SiegeModeCompatibilityModule.java
  src/main/java/pvpmode/compatibility/modules/siegeMode/SiegeModeCompatiblityModuleLoader.java
  src/main/java/pvpmode/compatibility/modules/siegeMode/SiegeZoneOverrideCondition.java
  src/main/java/pvpmode/compatibility/modules/suffixForge/SuffixForgeCompatibilityModuleLoader.java
  src/main/java/pvpmode/overrides/PvPOverrideManager.java
Labels: compatibility, new feature

#198 Outsourced the chat utility functions
  src/main/java/pvpmode/ChatUtils.java
  src/main/java/pvpmode/PvPEventHandler.java
  src/main/java/pvpmode/PvPUtils.java
  src/main/java/pvpmode/command/PvPCommand.java
  src/main/java/pvpmode/command/PvPCommandAdmin.java
  src/main/java/pvpmode/command/PvPCommandConfig.java
  src/main/java/pvpmode/command/PvPCommandHelp.java
  src/main/java/pvpmode/command/PvPCommandList.java
  src/main/java/pvpmode/compatibility/modules/lotr/LOTRModCompatibilityModule.java
  src/main/java/pvpmode/overrides/PvPOverrideManager.java
Labels: cleanup

#203 Made some chat messages more clear
  CHANGELOG.md
  src/main/java/pvpmode/PvPEventHandler.java
  src/main/java/pvpmode/command/AbstractPvPCommand.java
  src/main/java/pvpmode/compatibility/modules/lotr/LOTRModCompatibilityModule.java
Labels: improvement

#202 Pvphelp improvement
  CHANGELOG.md
  src/main/java/pvpmode/ChatUtils.java
  src/main/java/pvpmode/PvPMode.java
  src/main/java/pvpmode/command/AbstractPvPCommand.java
  src/main/java/pvpmode/command/PvPCommand.java
  src/main/java/pvpmode/command/PvPCommandAdmin.java
  src/main/java/pvpmode/command/PvPCommandConfig.java
  src/main/java/pvpmode/command/PvPCommandHelp.java
  src/main/java/pvpmode/command/PvPCommandList.java
Labels: improvement, new feature

#201 Added support for a configurable, global chat message prefix
  CHANGELOG.md
  src/main/java/pvpmode/ChatUtils.java
  src/main/java/pvpmode/PvPMode.java
  src/main/java/pvpmode/command/PvPCommandConfig.java
Labels: improvement

#204 Disabling the PvP radar now hides spying related information
  src/main/java/pvpmode/command/PvPCommand.java
  src/main/java/pvpmode/command/PvPCommandList.java
Labels: improvement

#206 Added /pvp info and /pvpadmin info
  CHANGELOG.md
  src/main/java/pvpmode/ChatUtils.java
  src/main/java/pvpmode/PvPUtils.java
  src/main/java/pvpmode/command/PvPCommand.java
  src/main/java/pvpmode/command/PvPCommandAdmin.java
Labels: new feature

#214 Replaced the default LOTR enemy biome override configuration file
  CHANGELOG.md
  src/main/java/pvpmode/PvPUtils.java
  src/main/java/pvpmode/compatibility/modules/lotr/LOTRModCompatibilityModule.java
  src/main/resources/assets/pvpmode/modules/lotr/default_enemy_biomes.txt
  src/main/resources/assets/pvpmode/modules/lotr/default_enemy_biomes_map.png
  src/main/resources/assets/pvpmode/modules/lotr/extended_enemy_biomes.txt
Labels: improvement

#213 The players in the warmup list in /pvplist are not sorted by their warmup timer
  CHANGELOG.md
  src/main/java/pvpmode/command/PvPCommandList.java
Labels: improvement

#212 Added full tab-complation support for all commands of the mod
  CHANGELOG.md
  src/main/java/pvpmode/command/PvPCommand.java
  src/main/java/pvpmode/command/PvPCommandAdmin.java
  src/main/java/pvpmode/command/PvPCommandConfig.java
  src/main/java/pvpmode/command/PvPCommandHelp.java
  src/main/java/pvpmode/command/PvPCommandList.java
Labels: improvement

#211 Updated a javadoc comment in the override manager
  src/main/java/pvpmode/overrides/PvPOverrideCondition.java
Labels: documentation

#216 The displayed PvP stats now only contain spying if it's enabled
  src/main/java/pvpmode/PvPUtils.java
Labels: bug

#223 Fixed an exception with /pvpadmin
  CHANGELOG.md
  src/main/java/pvpmode/command/PvPCommandAdmin.java
Labels: bug

#224 Fixed that the warmup timer was up to one second longer then specified
  CHANGELOG.md
  src/main/java/pvpmode/PvPEventHandler.java
Labels: bug
