Repository Lembas-Modding-Team/pvp-mode, pull requests merged in 2018-09, with the labels that each got.

#254 Fix #253
  CHANGELOG.md
  src/main/java/pvpmode/PvPUtils.java
Labels: improvement, low priority

#258 Added the PartialItemDropEvent classes
  src/main/java/pvpmode/PvPEventHandler.java
  src/main/java/pvpmode/PvPUtils.java
  src/main/java/pvpmode/compatibility/events/PartialItemDropEvent.java
Labels: cleanup

#257 Restructured the compatibility module system base classes
  src/main/java/pvpmode/compatibility/ForgeModCompatibilityModuleLoader.java
  src/main/java/pvpmode/compatibility/IdentifierCompatibilityModuleLoader.java
  src/main/java/pvpmode/compatibility/ModCompatibilityModuleLoader.java
  src/main/java/pvpmode/compatibility/modules/lotr/LOTRModCompatibilityModuleLoader.java
  src/main/java/pvpmode/compatibility/modules/siegeMode/SiegeModeCompatiblityModuleLoader.java
  src/main/java/pvpmode/compatibility/modules/suffixForge/SuffixForgeCompatibilityModuleLoader.java
Labels: cleanup

#264 Added support for the Ender IO soulbound enchantment
  CHANGELOG.md
  src/main/java/pvpmode/PvPMode.java
  src/main/java/pvpmode/compatibility/modules/enderio/EnderIOCompatibilityModule.java
  src/main/java/pvpmode/compatibility/modules/enderio/EnderIOCompatibilityModuleLoader.java
Labels: compatibility

#265 Added deathcraft compatibility
  CHANGELOG.md
  src/main/java/pvpmode/PvPMode.java
  src/main/java/pvpmode/compatibility/BukkitPluginCompatibilityModuleLoader.java
  src/main/java/pvpmode/compatibility/modules/deathcraft/DeathcraftCompatibilityModule.java
  src/main/java/pvpmode/compatibility/modules/deathcraft/DeathcraftCompatibilityModuleLoader.java
Labels: compatibility

#266 Added lootable bodies compatibility
  CHANGELOG.md
  src/main/java/pvpmode/PvPMode.java
  src/main/java/pvpmode/compatibility/modules/lootableBodies/LootableBodiesCompatibilityModule.java
  src/main/java/pvpmode/compatibility/modules/lootableBodies/LootableBodiesCompatibilityModuleLoader.java
  src/main/java/pvpmode/core/PvPModeClassTransformer.java
  src/main/java/pvpmode/core/PvPModeCore.java
Labels: compatibility

#277 Encapsulated the configuration properties
  CHANGELOG.md
  UPDATE_INSTRUCTIONS.md
  src/main/java/pvpmode/api/common/compatibility/AbstractCompatibilityModule.java
  src/main/java/pvpmode/api/common/compatibility/CompatibilityModule.java
  src/main/java/pvpmode/api/common/configuration/CommonConfiguration.java
  src/main/java/pvpmode/api/common/configuration/CommonConfigurationConstants.java
  src/main/java/pvpmode/api/server/compatibility/events/CombatLoggingHandlerRegistryEvent.java
  src/main/java/pvpmode/api/server/configuration/ServerConfiguration.java
  src/main/java/pvpmode/internal/common/CommonProxy.java
  src/main/java/pvpmode/internal/common/compatibility/CompatibilityManagerImpl.java
  src/main/java/pvpmode/internal/server/PvPDataImpl.java
  src/main/java/pvpmode/internal/server/PvPServerEventHandler.java
  src/main/java/pvpmode/internal/server/ServerProxy.java
  src/main/java/pvpmode/internal/server/command/PvPCommand.java
  src/main/java/pvpmode/internal/server/command/PvPCommandAdmin.java
  src/main/java/pvpmode/internal/server/command/PvPCommandConfig.java
  src/main/java/pvpmode/internal/server/command/PvPCommandList.java
  src/main/java/pvpmode/internal/server/configuration/ServerConfigurationImpl.java
  src/main/java/pvpmode/internal/server/log/CSVCombatLogHandler.java
  src/main/java/pvpmode/internal/server/overrides/OverrideManagerImpl.java
  src/main/java/pvpmode/internal/server/utils/PvPServerUtilsProvider.java
  src/main/java/pvpmode/internal/server/utils/ServerChatUtilsProvider.java
  src/main/java/pvpmode/modules/lotr/api/server/LOTRServerConfigurationConstants.java
  src/main/java/pvpmode/modules/lotr/internal/server/LOTRModCompatibilityModule.java
  src/main/java/pvpmode/modules/siegeMode/api/server/SiegeModeServerConfigurationConstants.java
  src/main/java/pvpmode/modules/siegeMode/internal/server/SiegeModeCompatibilityModule.java
  src/main/java/pvpmode/modules/suffixForge/api/server/SuffixForgeServerConfigurationConstants.java
  src/main/java/pvpmode/modules/suffixForge/internal/server/SuffixForgeCompatibilityModule.java
Labels: cleanup

#278 Renamed and recategorized some configuration properties
  UPDATE_INSTRUCTIONS.md
  src/main/java/pvpmode/api/server/configuration/ServerConfiguration.java
  src/main/java/pvpmode/internal/server/PvPServerEventHandler.java
  src/main/java/pvpmode/internal/server/ServerProxy.java
  src/main/java/pvpmode/internal/server/command/PvPCommand.java
  src/main/java/pvpmode/internal/server/command/PvPCommandConfig.java
  src/main/java/pvpmode/internal/server/command/PvPCommandList.java
  src/main/java/pvpmode/internal/server/configuration/ServerConfigurationImpl.java
  src/main/java/pvpmode/internal/server/utils/PvPServerUtilsProvider.java
  src/main/java/pvpmode/modules/lotr/api/server/LOTRServerConfigurationConstants.java
  src/main/java/pvpmode/modules/lotr/internal/server/LOTRModCompatibilityModule.java
  src/main/java/pvpmode/modules/siegeMode/api/server/SiegeModeServerConfigurationConstants.java
  src/main/java/pvpmode/modules/siegeMode/internal/server/SiegeModeCompatibilityModule.java
  src/main/java/pvpmode/modules/suffixForge/api/server/SuffixForgeServerConfigurationConstants.java
  src/main/java/pvpmode/modules/suffixForge/internal/server/SuffixForgeCompatibilityModule.java
Labels: cleanup

#279 Categorized all configuration entries
  UPDATE_INSTRUCTIONS.md
  src/main/java/pvpmode/api/server/configuration/ServerConfiguration.java
  src/main/java/pvpmode/internal/server/configuration/ServerConfigurationImpl.java
Labels: cleanup

#281 Fixed a NPE with deathcraft when a player with empty inventory dies
  CHANGELOG.md
  src/main/java/pvpmode/compatibility/modules/deathcraft/DeathcraftCompatibilityModule.java
Labels: bug
