Repository Lembas-Modding-Team/pvp-mode, pull requests merged in 2019-01, with the labels that each got.

#297 Closed #227
  src/main/java/pvpmode/api/common/overrides/EnumForcedPvPMode.java
  src/main/java/pvpmode/api/server/overrides/PvPOverrideCondition.java
  src/main/java/pvpmode/internal/server/overrides/OverrideManagerImpl.java
  src/main/java/pvpmode/modules/lotr/internal/server/HostileBiomeOverrideCondition.java
  src/main/java/pvpmode/modules/lotr/internal/server/MiddleEarthBiomeOverrideCondition.java
  src/main/java/pvpmode/modules/lotr/internal/server/SafeBiomeOverrideCondition.java
  src/main/java/pvpmode/modules/siegeMode/internal/server/SiegeZoneOverrideCondition.java
Labels: cleanup

#300 Closed #268
  CHANGELOG.md
  src/main/java/pvpmode/internal/common/compatibility/CompatibilityManagerImpl.java
Labels: cleanup

#301 Closed #263
  src/main/java/pvpmode/internal/server/ServerProxy.java
  src/main/java/pvpmode/modules/siegeMode/internal/server/SiegeModeCompatibilityModuleLoader.java
Labels: cleanup

#302 Fixed that the command arguments were parsed wrongly
  src/main/java/pvpmode/internal/server/command/AbstractPvPCommand.java
Labels: bug

#303 Closed #282
  CHANGELOG.md
  UPDATE_INSTRUCTIONS.md
  src/main/java/pvpmode/internal/server/ServerProxy.java
  src/main/java/pvpmode/internal/server/configuration/ServerConfigurationImpl.java
  src/main/java/pvpmode/modules/suffixForge/api/server/SuffixForgeServerConfiguration.java
  src/main/java/pvpmode/modules/suffixForge/internal/server/SuffixForgeCompatibilityModule.java
  src/main/java/pvpmode/modules/suffixForge/internal/server/SuffixForgeCompatibilityModuleLoader.java
  src/main/java/pvpmode/modules/suffixForge/internal/server/SuffixForgeServerConfigurationImpl.java
Labels: cleanup, compatibility

#306 Fixed a crash if the mod is installed clientside
  src/main/java/pvpmode/internal/common/core/PvPModeClassTransformer.java
  src/main/java/pvpmode/internal/common/core/PvPModeCore.java
Labels: bug

#307 Closed #215
  CHANGELOG.md
  UPDATE_INSTRUCTIONS.md
  src/main/java/pvpmode/internal/common/CommonProxy.java
  src/main/java/pvpmode/modules/lotr/internal/server/LOTRModCompatibilityModule.java
Labels: improvement

#309 Fixed #290
  CHANGELOG.md
  src/main/java/pvpmode/internal/server/command/SoulboundCommand.java
Labels: bug, needs testing

#308 Closed #293
  CHANGELOG.md
  src/main/java/pvpmode/internal/server/command/PvPCommandConfig.java
  src/main/java/pvpmode/internal/server/command/PvPCommandHelp.java
  src/main/java/pvpmode/internal/server/utils/PvPServerUtilsProvider.java
Labels: improvement

#298 Closed #285
  CHANGELOG.md
  src/main/java/pvpmode/internal/server/command/AbstractPvPCommand.java
  src/main/java/pvpmode/internal/server/command/PvPCommand.java
  src/main/java/pvpmode/internal/server/command/PvPCommandAdmin.java
  src/main/java/pvpmode/internal/server/command/PvPCommandConfig.java
  src/main/java/pvpmode/internal/server/command/PvPCommandHelp.java
  src/main/java/pvpmode/internal/server/command/PvPCommandList.java
  src/main/java/pvpmode/internal/server/command/SoulboundCommand.java
Labels: improvement

#313 Closed #256
  src/main/java/pvpmode/PvPMode.java
  src/main/java/pvpmode/api/common/compatibility/CompatibilityManager.java
  src/main/java/pvpmode/api/common/compatibility/CompatibilityModuleLoader.java
  src/main/java/pvpmode/api/common/compatibility/EnumCompatibilityModuleLoadingPoint.java
  src/main/java/pvpmode/api/common/utils/PvPCommonUtils.java
  src/main/java/pvpmode/api/server/compatibility/BukkitPluginCompatibilityModuleLoader.java
  src/main/java/pvpmode/api/server/compatibility/ServerCompatibilityConstants.java
  src/main/java/pvpmode/internal/common/CommonProxy.java
  src/main/java/pvpmode/internal/common/compatibility/CompatibilityManagerImpl.java
  src/main/java/pvpmode/internal/server/ServerProxy.java
  src/main/java/pvpmode/modules/citizens/internal/server/CitizensCompatibilityModuleLoader.java
  src/main/java/pvpmode/modules/deathcraft/internal/server/DeathcraftCompatibilityModuleLoader.java
Labels: cleanup, compatibility

#314 Closed #218
  src/main/java/pvpmode/api/server/compatibility/BukkitPluginCompatibilityModuleLoader.java
  src/main/java/pvpmode/internal/server/ServerProxy.java
  src/main/java/pvpmode/modules/bukkit/api/server/BukkitPluginCompatibilityModuleLoader.java
  src/main/java/pvpmode/modules/bukkit/internal/server/BukkitCompatibilityModule.java
  src/main/java/pvpmode/modules/bukkit/internal/server/BukkitCompatibilityModuleLoader.java
  src/main/java/pvpmode/modules/citizens/internal/server/CitizensCompatibilityModuleLoader.java
  src/main/java/pvpmode/modules/deathcraft/internal/server/DeathcraftCompatibilityModuleLoader.java
Labels: cleanup

#316 Closed #267
  CHANGELOG.md
  src/main/java/pvpmode/api/common/compatibility/CompatibilityModuleLoader.java
  src/main/java/pvpmode/api/common/compatibility/ForgeModCompatibilityModuleLoader.java
  src/main/java/pvpmode/api/common/compatibility/IdentifierCompatibilityModuleLoader.java
  src/main/java/pvpmode/internal/common/compatibility/CompatibilityManagerImpl.java
  src/main/java/pvpmode/modules/bukkit/api/server/BukkitPluginCompatibilityModuleLoader.java
  src/main/java/pvpmode/modules/bukkit/internal/server/BukkitCompatibilityModuleLoader.java
  src/main/java/pvpmode/modules/deathcraft/internal/server/DeathcraftCompatibilityModuleLoader.java
  src/main/java/pvpmode/modules/enderio/internal/server/EnderIOCompatibilityModuleLoader.java
  src/main/java/pvpmode/modules/lootableBodies/internal/server/LootableBodiesCompatibilityModuleLoader.java
  src/main/java/pvpmode/modules/lotr/internal/server/LOTRModCompatibilityModuleLoader.java
  src/main/java/pvpmode/modules/siegeMode/internal/server/SiegeModeCompatibilityModuleLoader.java
Labels: compatibility

#319 Fixed that the enemy/safe biome config files were recreated too often
  src/main/java/pvpmode/modules/lotr/internal/server/LOTRModCompatibilityModule.java
Labels: bug

#318 Fixed that the enemy/safe biome configs weren't reloaded everytime
  src/main/java/pvpmode/modules/lotr/internal/server/LOTRServerConfigurationImpl.java
Labels: bug

#327 Replace self-closing tags to maintain HTML4 compatibility.
  src/main/java/pvpmode/api/common/compatibility/CompatibilityModuleLoader.java
  src/main/java/pvpmode/api/common/utils/PvPCommonUtils.java
  src/main/java/pvpmode/api/server/compatibility/events/PartialItemDropEvent.java
  src/main/java/pvpmode/api/server/overrides/OverrideManager.java
  src/main/java/pvpmode/api/server/overrides/PvPOverrideCondition.java
  src/main/java/pvpmode/api/server/utils/PvPServerUtils.java
  src/main/java/pvpmode/modules/deathcraft/internal/server/DeathcraftCompatibilityModule.java
Labels: cleanup
